language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"
jobs:
  include:
    - python: "pypy3"
      env: NOMYPY=true
install:
  - pip install flake8
  - pip install mypy
script:
  - nosetests
  - flake8
  - "[[ \"$NOMYPY\" == true ]] || mypy arpy.py"
